"""DSL → executable script compilers (Playwright / PyTest-API / SQL)."""
from __future__ import annotations

from typing import Any

from app.modules.no_code_flows.models import FlowRuntime


def _q(value: Any) -> str:
    """Safely format a Python literal."""
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def compile_playwright(flow: dict[str, Any]) -> tuple[str, list[str]]:
    warnings: list[str] = []
    name = flow.get("flow_name") or "no_code_flow"
    steps = flow.get("steps", [])

    lines: list[str] = [
        '"""Auto-generated by QualityForge AI from no-code DSL."""',
        "from playwright.sync_api import sync_playwright, expect",
        "",
        "",
        "def run_test() -> None:",
        f'    """Flow: {name}"""',
        "    with sync_playwright() as p:",
        "        browser = p.chromium.launch(headless=True)",
        "        context = browser.new_context()",
        "        page = context.new_page()",
        "        try:",
    ]

    for step in steps:
        step_type = (step.get("type") or "").lower()
        cfg = step.get("config", {}) or {}
        if step_type == "open_page":
            lines.append(f"            page.goto({_q(cfg.get('url'))})")
        elif step_type == "input":
            lines.append(f"            page.fill({_q(cfg.get('selector'))}, {_q(cfg.get('value'))})")
        elif step_type == "click":
            lines.append(f"            page.click({_q(cfg.get('selector'))})")
        elif step_type == "wait":
            lines.append(f"            page.wait_for_timeout({int(cfg.get('ms', 1000))})")
        elif step_type == "wait_for_selector":
            lines.append(f"            page.wait_for_selector({_q(cfg.get('selector'))})")
        elif step_type == "assert_visible":
            lines.append(f"            expect(page.locator({_q(cfg.get('selector'))})).to_be_visible()")
        elif step_type == "assert_text":
            lines.append(
                f"            expect(page.locator({_q(cfg.get('selector'))})).to_have_text({_q(cfg.get('value'))})"
            )
        elif step_type == "screenshot":
            target = cfg.get("path", f"/tmp/{name}.png")
            lines.append(f"            page.screenshot(path={_q(target)})")
        else:
            warnings.append(f"Unknown step type ignored: {step_type!r}")

    lines += [
        "        finally:",
        "            context.close()",
        "            browser.close()",
        "",
        "",
        'if __name__ == "__main__":',
        "    run_test()",
    ]
    return "\n".join(lines), warnings


def compile_pytest_api(flow: dict[str, Any]) -> tuple[str, list[str]]:
    warnings: list[str] = []
    name = flow.get("flow_name", "api_flow").replace(" ", "_").lower()
    steps = flow.get("steps", [])

    lines = [
        '"""Auto-generated API test by QualityForge AI."""',
        "import httpx",
        "",
        "",
        f"def test_{name}() -> None:",
        "    response = None",
        "    response_json = {}",
    ]

    for step in steps:
        step_type = (step.get("type") or "").lower()
        cfg = step.get("config", {}) or {}
        if step_type == "api_request":
            method = (cfg.get("method") or "GET").lower()
            url = cfg.get("url")
            headers = cfg.get("headers") or {}
            body = cfg.get("body")
            lines.append(
                f"    response = httpx.{method}({_q(url)}, headers={headers!r}, json={body!r}, timeout=30)"
            )
            lines.append("    try:\n        response_json = response.json()\n    except Exception:\n        response_json = {}")
        elif step_type == "assert_status_code":
            lines.append(f"    assert response is not None and response.status_code == {int(cfg.get('expected', 200))}")
        elif step_type == "assert_json_path":
            path = cfg.get("path", "$")
            condition = (cfg.get("condition") or "exists").lower()
            keys = [p for p in path.replace("$.", "").split(".") if p]
            access = "response_json"
            for k in keys:
                access += f".get({_q(k)}, {{}}) if isinstance({access}, dict) else {{}}"
            if condition == "exists":
                lines.append(f"    assert {access} not in (None, '', {{}}, [])")
            elif condition == "equals":
                lines.append(f"    assert {access} == {cfg.get('value')!r}")
            else:
                warnings.append(f"Unknown json-path condition: {condition}")
        else:
            warnings.append(f"Unknown step type ignored: {step_type!r}")
    return "\n".join(lines), warnings


def compile_sql(flow: dict[str, Any]) -> tuple[str, list[str]]:
    return flow.get("query", "-- empty query"), []


def compile_flow(flow: dict[str, Any], runtime: FlowRuntime) -> tuple[str, list[str]]:
    if runtime == FlowRuntime.PLAYWRIGHT:
        return compile_playwright(flow)
    if runtime == FlowRuntime.PYTEST_API:
        return compile_pytest_api(flow)
    if runtime == FlowRuntime.SQL:
        return compile_sql(flow)
    raise ValueError(f"Unsupported runtime: {runtime}")
